log_dir: "/micklem/data/download_logs"
data_dir: "/micklem/data"

default_sources:
  - "BioGRID"
  - "GOAnnotation"
  - "IntAct"
  - "IntactVocabulary"
  - "InterPro"
  - "InterProGO"
  - "NCBIGene"
  - "PDB"
  - "PubMed"
  - "Reactome"
  - "UniProt"
  - "GenBank"

UniProt:
    organisms:
        - 83333
        - 511145
        - 1423
        - 224308
    excluded_organisms:
        - 10091
        - 10092
        - 35531
        - 39442
        - 46244
        - 57486
        - 63221
        - 116058
        - 180454
        - 377270
        - 377271
        - 377586
        - 377587
        - 943925
        - 943926
        - 316385
        - 1110693
        - 527799
        - 595496

GenBank:
    organisms:
        Bacteria:
          - Bacillus_subtilis_168_uid57675
          - Escherichia_coli_K_12_substr__MG1655_uid57779

